### ISSUE TITLE
Entities created do not show up in the hierarchy

### ISSUE THREAD

**Issue by justinISOFORM** [leonidaspir/uranus-editor-scripting#8]
I was able to get the editor to run and I see the objects in the scene, however the hierarchy does not update with the entities that were created.

**Comment by leonidaspir** [comment]
Hi @justinISOFORM,

How are you creating the entities? Are you using the editor API?

This framework doesn't do anything special on that matter. It will execute your PlayCanvas scripts in editor together with some helpful callbacks.

To add entities to the hierarchy you have to use the unofficial PlayCanvas editor API, you can find more info about it here:

https://forum.playcanvas.com/t/scripting-the-playcanvas-editor/2315

**Comment by justinISOFORM** [comment]
Ok, I think I understand. The syntax of instantiating entities via the PlayCanvas editor API isn't very clear to me. Do you happen to know if I could clone the entity via the JavaScript console and then hopefully the hierarchy would display properly for the cloned entity?

**Comment by leonidaspir** [comment]
For cloning an entity there isn't any API from what I know, so sadly that is not possible. You will have to study the `editor.js` code of the PlayCanvas editor (it's unminified on purpose so you can do that) and look on how cloning works there. And try  to replicate that in the console.
